name: Auto Translate

on:
  push:
    branches: ["main"]
    paths:
      - "lang/en.json"
      - "overwrite/**"
      - ".github/workflows/auto-translate.yml"
  workflow_dispatch:

concurrency:
  group: "AutoTranslate"
  cancel-in-progress: true

jobs:
  AutoTranslate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Run Auto Translate
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: |
          while read lang
            do
              node translate.js $lang
            done < langs.txt

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Push to Github
        run: |
          git config --global user.name "PrankGGBot"
          git config --global user.email "${{secrets.GH_BOT_EMAIL}}"
          git pull
          git add -A
          git commit -m "Update Translations from ${{ github.event.head_commit.id }}"
          git push
